/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import hospital.reception.reception_page;

/**
 *
 * @author pramodaya jayalath
 */
public class register_page extends javax.swing.JFrame {

    /**
     * Creates new form register_page
     */
    public register_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpatientstest = new javax.swing.JTextField();
        txtpatientsregistrationid = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnenter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtpatientsprescribedtreatments = new javax.swing.JTextField();
        btnlogoff = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Patient Details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 120, 330, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter the patient's registration id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 240, 300, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Enter the patient's test");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 310, 260, 40);

        txtpatientstest.setBackground(new java.awt.Color(153, 255, 153));
        txtpatientstest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtpatientstest);
        txtpatientstest.setBounds(540, 320, 670, 30);

        txtpatientsregistrationid.setBackground(new java.awt.Color(153, 255, 153));
        txtpatientsregistrationid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpatientsregistrationid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientsregistrationidActionPerformed(evt);
            }
        });
        getContentPane().add(txtpatientsregistrationid);
        txtpatientsregistrationid.setBounds(540, 250, 670, 30);

        btnclear.setBackground(new java.awt.Color(51, 255, 102));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(1070, 500, 140, 30);

        btnenter.setBackground(new java.awt.Color(51, 255, 102));
        btnenter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnenter.setText("Enter");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        getContentPane().add(btnenter);
        btnenter.setBounds(840, 500, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Details of the prescribed treatments");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 380, 340, 40);

        txtpatientsprescribedtreatments.setBackground(new java.awt.Color(153, 255, 153));
        txtpatientsprescribedtreatments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtpatientsprescribedtreatments);
        txtpatientsprescribedtreatments.setBounds(540, 390, 670, 30);

        btnlogoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogoff.setForeground(new java.awt.Color(255, 0, 0));
        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/13165939071654987882logout-md.png"))); // NOI18N
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogoff);
        btnlogoff.setBounds(1230, 30, 70, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("UCLA Medical Center");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 30, 500, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/green_background_2-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 0, 1340, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
        //enter data:
        
        //get the input
        String registrationid =txtpatientsregistrationid.getText();
        String test=txtpatientstest.getText();
        String prescribedtreatments=txtpatientsprescribedtreatments.getText();
        
        
        try{
            //create a database connetion
            Class.forName("java.sql.Driver");
            String path="jdbc:mysql://localhost/hospital_database";
            String user="root";
            String pass="root";
            Connection con = DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement();
            
            //inset data to the table
            String query ="update patient set Tests='"+test+"'  where Reg_id='"+registrationid+"' ";
            stmt.executeUpdate(query);
            String query1 ="update patient set Prescribed_treatments='"+prescribedtreatments+"'  where Reg_id='"+registrationid+"' ";
            stmt.executeUpdate(query1);
            
            //confirmation message
            JOptionPane.showMessageDialog(null,"Succesfully inserted");
            
            //clear text box
            txtpatientsregistrationid.setText("");
            txtpatientstest.setText("");
            txtpatientsprescribedtreatments.setText("");
      
        
        }catch(Exception ex){
            //error message
            JOptionPane.showMessageDialog(null,"Error Found"+ex);
        }
        
        
    }//GEN-LAST:event_btnenterActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        //clear text box:
        txtpatientsregistrationid.setText("");
        txtpatientstest.setText("");
        txtpatientsprescribedtreatments.setText("");
      
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        // hide this and go to login frame:
        this.hide();
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnlogoffActionPerformed

    private void txtpatientsregistrationidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientsregistrationidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientsregistrationidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnlogoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtpatientsprescribedtreatments;
    private javax.swing.JTextField txtpatientsregistrationid;
    private javax.swing.JTextField txtpatientstest;
    // End of variables declaration//GEN-END:variables
}
