/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.admin;

import hospital.Login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pramodaya jayalath
 */
public class create_salary_admin extends javax.swing.JFrame {

    /**
     * Creates new form create_salary_admin
     */
    public create_salary_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnlogoff = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtendyear = new javax.swing.JLabel();
        txtenddate = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        txtempid = new javax.swing.JTextField();
        btncreatesalary = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        txtendyear1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Create Salary");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 30, 340, 70);

        btnlogoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogoff.setForeground(new java.awt.Color(255, 0, 0));
        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/13165939071654987882logout-md.png"))); // NOI18N
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogoff);
        btnlogoff.setBounds(1240, 30, 70, 70);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 0, 0));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/home.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(1160, 30, 70, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Range");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 240, 240, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Employee Id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 180, 240, 30);

        txtendyear.setBackground(new java.awt.Color(153, 255, 153));
        txtendyear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtendyear.setText("Rs :");
        jPanel1.add(txtendyear);
        txtendyear.setBounds(460, 490, 80, 30);

        txtenddate.setBackground(new java.awt.Color(0, 255, 102));
        txtenddate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtenddate.setText("2017-05-05");
        txtenddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenddateActionPerformed(evt);
            }
        });
        jPanel1.add(txtenddate);
        txtenddate.setBounds(750, 300, 190, 30);

        txtsalary.setBackground(new java.awt.Color(153, 255, 153));
        txtsalary.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtsalary);
        txtsalary.setBounds(520, 490, 350, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(320, 300, 120, 30);

        txtstartdate.setBackground(new java.awt.Color(153, 255, 153));
        txtstartdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtstartdate.setText("2017-05-01");
        jPanel1.add(txtstartdate);
        txtstartdate.setBounds(450, 300, 190, 30);

        txtempid.setBackground(new java.awt.Color(153, 255, 153));
        txtempid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtempid);
        txtempid.setBounds(370, 180, 570, 30);

        btncreatesalary.setBackground(new java.awt.Color(51, 255, 102));
        btncreatesalary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncreatesalary.setText("Create Salary");
        btncreatesalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatesalaryActionPerformed(evt);
            }
        });
        jPanel1.add(btncreatesalary);
        btncreatesalary.setBounds(130, 490, 240, 40);

        btnclear.setBackground(new java.awt.Color(51, 255, 102));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(790, 350, 150, 40);

        txtendyear1.setBackground(new java.awt.Color(153, 255, 153));
        txtendyear1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtendyear1.setText("To");
        jPanel1.add(txtendyear1);
        txtendyear1.setBounds(650, 300, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/green_background_2-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // hide this and go to home page of admin:
        this.hide();
        admin_page admin=new admin_page();
        admin.setVisible(true);
        
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        // hide this and go to login page with logout:
         this.hide();
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnlogoffActionPerformed

    private void btncreatesalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatesalaryActionPerformed
        // create salary and show:
        String id =txtempid.getText();
        String startdate=txtstartdate.getText();
        String enddate=txtenddate.getText();
        txtsalary.setText("");
        
        
        
        
        try{
        
            Class.forName("java.sql.Driver");
            String path="jdbc:mysql://localhost/hospital_database"; 
            String user="root";
            String pass="root";
            //create a database connection:
            Connection con = DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement();
            
            //get the total work hours from  employee table in database
            String query1="select sum(Worked_hrs) AS total_sum from employee_attendence where (Employee_id='"+id+"') and DATE_FORMAT(Date, '%Y-%m-%d') between '"+startdate+"' and '"+enddate+"'";
            ResultSet rs1=stmt.executeQuery(query1);
            
            double total_worked_hours=0;
            
            //get the total works hours as integer:          
            while (rs1.next()){
                total_worked_hours+=Double.parseDouble(rs1.getString("total_sum"));
            }
            
            
            //get the employee salary per hour from employee details in the tables        
            String query2="select Employee_salary_per_hr as empsalary from employee where Employee_id='"+id+"'";
            ResultSet rs2=stmt.executeQuery(query2);
            
            //get the employee salary per hour as integer
            double salary_per_hour=0;
            while (rs2.next()){
                salary_per_hour+=Double.parseDouble(rs2.getString("empsalary")); 
            }
            
            //calculate the totla salary
            Double total_salary_per_date_range=total_worked_hours*salary_per_hour;
            
            //set the total salary to visible in the text box
            txtsalary.setText(""+total_salary_per_date_range);
                
           //show confirmation dialogue box
            JOptionPane.showMessageDialog(null,"Succesfully Calculated");

                 
        }catch(Exception ex){
            //show if there is an error:
            JOptionPane.showMessageDialog(null,"Error Found"+ex);
        }
    }//GEN-LAST:event_btncreatesalaryActionPerformed

    private void txtenddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenddateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // clear data in the text box:
        txtempid.setText("");
        txtsalary.setText("");
        txtstartdate.setText("");
        txtenddate.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_salary_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_salary_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_salary_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_salary_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_salary_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncreatesalary;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JLabel txtendyear;
    private javax.swing.JLabel txtendyear1;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtstartdate;
    // End of variables declaration//GEN-END:variables
}
