/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.admin;

import hospital.*;
import hospital.Login;
import hospital.admin.admin_page;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pramodaya jayalath
 */
public class employee_registration_admin_frame extends javax.swing.JFrame {

    /**
     * Creates new form employee_registration_frame
     */
    public employee_registration_admin_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtemployeelastname = new javax.swing.JTextField();
        txtemployeeaddress = new javax.swing.JTextField();
        txtemployeephone = new javax.swing.JTextField();
        txtemployeesalarypermonth = new javax.swing.JTextField();
        txtemployeenationalid = new javax.swing.JTextField();
        txtemployeefirstname = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnlogoff = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        comboboxemployeeward = new javax.swing.JComboBox<>();
        comboboxemployeeposition = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Employee Registration");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 30, 400, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Employee Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 260, 210, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Employee Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 310, 210, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Employee Phone");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 360, 210, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Employee Position");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 410, 210, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Employee Ward");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 460, 210, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Employee Salary per hour");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(230, 500, 260, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Employee National ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 160, 210, 40);

        txtemployeelastname.setBackground(new java.awt.Color(153, 255, 153));
        txtemployeelastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtemployeelastname);
        txtemployeelastname.setBounds(530, 270, 590, 30);

        txtemployeeaddress.setBackground(new java.awt.Color(153, 255, 153));
        txtemployeeaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtemployeeaddress);
        txtemployeeaddress.setBounds(530, 310, 590, 30);

        txtemployeephone.setBackground(new java.awt.Color(153, 255, 153));
        txtemployeephone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemployeephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemployeephoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtemployeephone);
        txtemployeephone.setBounds(530, 360, 590, 30);

        txtemployeesalarypermonth.setBackground(new java.awt.Color(153, 255, 153));
        txtemployeesalarypermonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtemployeesalarypermonth);
        txtemployeesalarypermonth.setBounds(530, 510, 590, 30);

        txtemployeenationalid.setBackground(new java.awt.Color(153, 255, 153));
        txtemployeenationalid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtemployeenationalid);
        txtemployeenationalid.setBounds(530, 170, 590, 30);

        txtemployeefirstname.setBackground(new java.awt.Color(153, 255, 153));
        txtemployeefirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtemployeefirstname);
        txtemployeefirstname.setBounds(530, 220, 590, 30);

        btnclear.setBackground(new java.awt.Color(51, 255, 102));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(740, 630, 280, 50);

        btnsave.setBackground(new java.awt.Color(51, 255, 102));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(430, 630, 280, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Employee First Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 210, 210, 40);

        btnlogoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogoff.setForeground(new java.awt.Color(255, 0, 0));
        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/13165939071654987882logout-md.png"))); // NOI18N
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogoff);
        btnlogoff.setBounds(1250, 30, 70, 70);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 0, 0));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/home.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(1170, 30, 70, 70);

        comboboxemployeeward.setBackground(new java.awt.Color(0, 255, 0));
        comboboxemployeeward.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxemployeeward.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Maternity", "Pediatrics", "Oncology", "Gynecologyst" }));
        comboboxemployeeward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxemployeewardActionPerformed(evt);
            }
        });
        jPanel1.add(comboboxemployeeward);
        comboboxemployeeward.setBounds(530, 460, 590, 30);

        comboboxemployeeposition.setBackground(new java.awt.Color(0, 255, 0));
        comboboxemployeeposition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxemployeeposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Doctor", "Reception", "Nurse", "Pharmacy Staff" }));
        comboboxemployeeposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxemployeepositionActionPerformed(evt);
            }
        });
        jPanel1.add(comboboxemployeeposition);
        comboboxemployeeposition.setBounds(530, 410, 590, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/green_background_2-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // get the employee details and register him/her:
        String id =txtemployeenationalid.getText();
        String fname=txtemployeefirstname.getText();
        String lname=txtemployeelastname.getText();
        String address =txtemployeeaddress.getText();
        String phone =txtemployeephone.getText();
        String position =comboboxemployeeposition.getSelectedItem().toString();
        String ward =comboboxemployeeward.getSelectedItem().toString();
        String salary=txtemployeesalarypermonth.getText();
        
        
        try{
            
            //create a database connection:
            Class.forName("java.sql.Driver");
            String path="jdbc:mysql://localhost/hospital_database";
            String user="root";
            String pass="root";
            Connection con = DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement();
            
            //store data in the employee table
            String query ="insert into employee(Employee_national_id,Employee_first_name,Employee_last_name,Employee_address,Employee_phone,Employee_position,Employee_ward,Employee_salary_per_hr) values('"+id+"','"+fname+"','"+lname+"','"+address+"','"+phone+"','"+position+"','"+ward+"','"+salary+"')";
            stmt.executeUpdate(query);
            
            //show confirmation message
            JOptionPane.showMessageDialog(null,"Succesfully inserted");
            
            //clear the text box after inserted data in the table:
            txtemployeenationalid.setText("");
            txtemployeelastname.setText("");
            txtemployeefirstname.setText("");
            txtemployeeaddress.setText("");
            txtemployeephone.setText("");
            
            
            txtemployeesalarypermonth.setText("");

        
        
        }catch(Exception ex){
            //error message
            JOptionPane.showMessageDialog(null,"Error Found"+ex);
        }
        
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // clear text box:
        txtemployeenationalid.setText("");
        txtemployeelastname.setText("");
        txtemployeefirstname.setText("");
        txtemployeeaddress.setText("");
        txtemployeephone.setText("");
        txtemployeesalarypermonth.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtemployeephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployeephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeephoneActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // hide this and go to admin home page:
        this.hide();
        admin_page admin=new admin_page();
        admin.setVisible(true);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        // hide this and go to the lonin page:
         this.hide();
        Login log=new Login();
        log.setVisible(true);
        
    }//GEN-LAST:event_btnlogoffActionPerformed

    private void comboboxemployeepositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxemployeepositionActionPerformed
        // use a combobox for employee position :
    }//GEN-LAST:event_comboboxemployeepositionActionPerformed

    private void comboboxemployeewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxemployeewardActionPerformed
        // use a combobox for employee ward:
    }//GEN-LAST:event_comboboxemployeewardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_registration_admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_registration_admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_registration_admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_registration_admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_registration_admin_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogoff;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> comboboxemployeeposition;
    private javax.swing.JComboBox<String> comboboxemployeeward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtemployeeaddress;
    private javax.swing.JTextField txtemployeefirstname;
    private javax.swing.JTextField txtemployeelastname;
    private javax.swing.JTextField txtemployeenationalid;
    private javax.swing.JTextField txtemployeephone;
    private javax.swing.JTextField txtemployeesalarypermonth;
    // End of variables declaration//GEN-END:variables
}
