/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.admin;

import hospital.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author pramodaya jayalath
 */
public class mark_attendence_admin extends javax.swing.JFrame {
             
    /**
     * Creates new form mark_attendence
     *      */
    
    //crate a date class
    Date date = new Date();
    
    //get the today date
    private static final DateFormat type_date = new SimpleDateFormat("yyyy/MM/dd");
    String todaydate=type_date.format(date).toString();
    
    public mark_attendence_admin() {
        initComponents();
        
        //set txtdate as todaydate
        txtdate.setText(todaydate); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txtempid = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnmark = new javax.swing.JButton();
        btnlogoff = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtleavetime = new javax.swing.JTextField();
        txtattendtime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Employee Attendence ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 90, 430, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Leave Time");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 360, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Employee ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 210, 180, 30);

        txtdate.setBackground(new java.awt.Color(153, 255, 153));
        txtdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        jPanel1.add(txtdate);
        txtdate.setBounds(520, 260, 220, 30);

        txtempid.setBackground(new java.awt.Color(153, 255, 153));
        txtempid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempid);
        txtempid.setBounds(520, 210, 220, 30);

        btnclear.setBackground(new java.awt.Color(51, 255, 102));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(600, 440, 140, 40);

        btnmark.setBackground(new java.awt.Color(51, 255, 102));
        btnmark.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnmark.setText("Mark");
        btnmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarkActionPerformed(evt);
            }
        });
        jPanel1.add(btnmark);
        btnmark.setBounds(440, 440, 140, 40);

        btnlogoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogoff.setForeground(new java.awt.Color(255, 0, 0));
        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/13165939071654987882logout-md.png"))); // NOI18N
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogoff);
        btnlogoff.setBounds(1230, 30, 70, 70);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 0, 0));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/home.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(1150, 30, 70, 70);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Attend Time");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 310, 180, 30);

        txtleavetime.setBackground(new java.awt.Color(153, 255, 153));
        txtleavetime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtleavetime.setText("hrs:min:Am/Pm");
        jPanel1.add(txtleavetime);
        txtleavetime.setBounds(520, 360, 220, 30);

        txtattendtime.setBackground(new java.awt.Color(153, 255, 153));
        txtattendtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtattendtime.setText("hrs:min:Am/Pm");
        jPanel1.add(txtattendtime);
        txtattendtime.setBounds(520, 310, 220, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 260, 180, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/green_background_2-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // hide this and go to home page of admin:
        this.hide();
        admin_page admin=new admin_page();
        admin.setVisible(true);

    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        // hide this and go to login frame:
        this.hide();
        Login log=new Login();
        log.setVisible(true);

    }//GEN-LAST:event_btnlogoffActionPerformed

    private void btnmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarkActionPerformed
        // mark attendence:
       
        String id =txtempid.getText();
        String tdate=txtdate.getText();
        
        String timein=txtattendtime.getText();
        String timeout=txtleavetime.getText();
                
        
        //calculate the worked time 
        int timeinhrs=8;
        int timeinmunites=30;
        int timeouthrs=10;
        int timeoutmunites=30;
        
        
        //get the time in as hours and munites
        String timeinfirst="";
        String timeinsecond="";
        for(int i=0;i<timein.length();i++){
            if(timein.charAt(i)!=':'){
                timeinfirst+=timein.charAt(i);
            }else{
                
                for(int j=i+1;j<timein.length();j++){
                    if(timein.charAt(j)!=':'){
                        timeinsecond+=""+timein.charAt(j);
                    }else{
                        break;
                    }
                }
                break;
               
            }
        }
        
        //convert it into integers
        timeinhrs=Integer.parseInt(timeinfirst);
        timeinmunites=Integer.parseInt(timeinsecond);
        
        
        //get the out time as hours and munites
        String timeoutfirst="";
        String timeoutsecond="";
        for(int i=0;i<timeout.length();i++){
            if(timeout.charAt(i)!=':'){
                timeoutfirst+=timeout.charAt(i);
            }else{
                
                for(int j=i+1;j<timeout.length();j++){
                    if(timeout.charAt(j)!=':'){
                        timeoutsecond+=""+timeout.charAt(j);
                    }else{
                        break;
                    }
                }
                break;
               
            }
        }
        
        //convert it into integers
        timeouthrs=Integer.parseInt(timeoutfirst);
        timeoutmunites=Integer.parseInt(timeoutsecond);
        
        
        
        //calculate the worked time as double
        if(timeinmunites>timeoutmunites){
            timeouthrs-=1;
            timeoutmunites+=60;
        }
        
        double total_hrs=(double)timeouthrs-(double)timeinhrs;
        double total_munites=(double)timeoutmunites-(double)timeinmunites;
        double total_munites_as_hrs=(double)total_munites/60;
        
        double int_work_hrs=total_hrs+total_munites_as_hrs;
        
        //convert double into two decimal points
        DecimalFormat df = new DecimalFormat("#.##");      
        int_work_hrs = Double.valueOf(df.format(int_work_hrs));
        
        
        try{
            
            //create a database connection
            Class.forName("java.sql.Driver");
            String path="jdbc:mysql://localhost/hospital_database";
            String user="root";
            String pass="root";
            Connection con = DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement();
            
            //store data in the employee_attendence table
            String query ="insert into employee_attendence(Employee_id,Date,Attend_time,Leave_time,Worked_hrs) values('"+id+"','"+tdate+"','"+timein+"','"+timeout+"','"+int_work_hrs+"')";
            stmt.executeUpdate(query);
            
            //confirmation message
            JOptionPane.showMessageDialog(null,"Succesfully inserted");

            //clear after inserted
            txtempid.setText("");
            
            
        }catch(Exception ex){
            //error message if there any errors
            JOptionPane.showMessageDialog(null,"Error Found"+ex);
        }

    }//GEN-LAST:event_btnmarkActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // clear text box:
        txtempid.setText("");
        txtattendtime.setText("");
        txtleavetime.setText("");
        
       

    }//GEN-LAST:event_btnclearActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mark_attendence_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mark_attendence_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mark_attendence_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mark_attendence_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mark_attendence_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogoff;
    private javax.swing.JButton btnmark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtattendtime;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtleavetime;
    // End of variables declaration//GEN-END:variables
}
