/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.admin;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import hospital.*;

/**
 *
 * @author pramodaya jayalath
 */
public class show_employee_information extends javax.swing.JFrame {

    /**
     * Creates new form show_employee_information
     */
    public show_employee_information() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtempfirstname = new javax.swing.JTextField();
        txtemplastname = new javax.swing.JTextField();
        txtempaddress = new javax.swing.JTextField();
        txtempphone = new javax.swing.JTextField();
        txtempposition = new javax.swing.JTextField();
        txtempward = new javax.swing.JTextField();
        txtempsalaryperhour = new javax.swing.JTextField();
        txtempid = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtempnationalid = new javax.swing.JTextField();
        txtempfirstname1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnlogoff = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Employee Information");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 30, 370, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Employee ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 140, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Employee First Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 180, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Employee Ward");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 540, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Employee Salary Per Hour");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 580, 260, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Employee Last Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 330, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Employee Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 410, 220, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Employee Phone");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 450, 220, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Employee Position");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 500, 220, 30);

        txtempfirstname.setBackground(new java.awt.Color(153, 255, 153));
        txtempfirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempfirstname);
        txtempfirstname.setBounds(490, 180, 530, 30);

        txtemplastname.setBackground(new java.awt.Color(153, 255, 153));
        txtemplastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtemplastname);
        txtemplastname.setBounds(490, 330, 530, 30);

        txtempaddress.setBackground(new java.awt.Color(153, 255, 153));
        txtempaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempaddress);
        txtempaddress.setBounds(490, 410, 530, 30);

        txtempphone.setBackground(new java.awt.Color(153, 255, 153));
        txtempphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempphone);
        txtempphone.setBounds(490, 450, 530, 30);

        txtempposition.setBackground(new java.awt.Color(153, 255, 153));
        txtempposition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempposition);
        txtempposition.setBounds(490, 490, 530, 30);

        txtempward.setBackground(new java.awt.Color(153, 255, 153));
        txtempward.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempward);
        txtempward.setBounds(490, 530, 530, 30);

        txtempsalaryperhour.setBackground(new java.awt.Color(153, 255, 153));
        txtempsalaryperhour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempsalaryperhour);
        txtempsalaryperhour.setBounds(490, 580, 530, 30);

        txtempid.setBackground(new java.awt.Color(153, 255, 153));
        txtempid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempid);
        txtempid.setBounds(490, 140, 530, 30);

        btnclear.setBackground(new java.awt.Color(51, 255, 102));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(800, 240, 220, 40);

        btnsearch.setBackground(new java.awt.Color(51, 255, 102));
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch);
        btnsearch.setBounds(540, 240, 220, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Employee National Id");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(200, 370, 220, 30);

        txtempnationalid.setBackground(new java.awt.Color(153, 255, 153));
        txtempnationalid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempnationalid);
        txtempnationalid.setBounds(490, 370, 530, 30);

        txtempfirstname1.setBackground(new java.awt.Color(0, 255, 0));
        txtempfirstname1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtempfirstname1);
        txtempfirstname1.setBounds(490, 180, 530, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("OR");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1070, 140, 60, 30);

        btnlogoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogoff.setForeground(new java.awt.Color(255, 0, 0));
        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/13165939071654987882logout-md.png"))); // NOI18N
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogoff);
        btnlogoff.setBounds(1260, 20, 70, 70);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 0, 0));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/home.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(1180, 20, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/green_background_2-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // search employee:
        
        String id=txtempid.getText();
        String fname=txtempfirstname.getText();
        
        try{
            //create a database connection
            Class.forName("java.sql.Driver");
            String path="jdbc:mysql://localhost/hospital_database";
            String user="root";
            String pass="root";
            Connection con = DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement();
            
            //select data from the employe table
            String query ="select * from employee where Employee_id='"+id+"' or Employee_first_name='"+fname+"'";
            ResultSet rs=stmt.executeQuery(query);
            
            //set the text box by using fetched data
            while(rs.next()){
                txtempnationalid.setText(rs.getString("Employee_national_id"));
                txtemplastname.setText(rs.getString("Employee_last_name"));
                txtempid.setText(rs.getString("Employee_id"));
                txtempfirstname.setText(rs.getString("Employee_first_name"));
                txtempaddress.setText(rs.getString("Employee_address"));
                txtempphone.setText(rs.getString("Employee_phone"));
                txtempposition.setText(rs.getString("Employee_position"));
                txtemplastname.setText(rs.getString("Employee_last_name"));
                txtempward.setText(rs.getString("Employee_ward"));
                txtempsalaryperhour.setText(rs.getString("Employee_salary_per_hr"));
                
                
                
            }
        }catch(ClassNotFoundException | SQLException ex){
            //error message
            JOptionPane.showMessageDialog(null,"Error Found"+ex);
        }
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       //clear text box
        
        txtempid.setText("");
        txtempnationalid.setText("");
        txtempfirstname.setText("");
        txtemplastname.setText(""); 
        txtempaddress.setText("");
        txtempphone.setText("");
        txtempposition.setText("");
        txtemplastname.setText("");
        txtempward.setText("");
        txtempsalaryperhour.setText("");
                
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // hide this and go to home page of admin:
        this.hide();
        admin_page admin=new admin_page();
        admin.setVisible(true);
        
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        // hide this and got to login frame:
         this.hide();
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnlogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show_employee_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show_employee_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show_employee_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show_employee_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show_employee_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogoff;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtempaddress;
    private javax.swing.JTextField txtempfirstname;
    private javax.swing.JTextField txtempfirstname1;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtemplastname;
    private javax.swing.JTextField txtempnationalid;
    private javax.swing.JTextField txtempphone;
    private javax.swing.JTextField txtempposition;
    private javax.swing.JTextField txtempsalaryperhour;
    private javax.swing.JTextField txtempward;
    // End of variables declaration//GEN-END:variables
}
