/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.admin;

import hospital.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pramodaya jayalath
 */
public class show_patient_information_admin extends javax.swing.JFrame {

    /**
     * Creates new form show_patient_information
     */
    public show_patient_information_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtplastname = new javax.swing.JTextField();
        txtpaddress = new javax.swing.JTextField();
        txtptelephone = new javax.swing.JTextField();
        txtrecommendedpersonid = new javax.swing.JTextField();
        txtrecommendedpersonname = new javax.swing.JTextField();
        txtpward = new javax.swing.JTextField();
        txtpregistrationdate = new javax.swing.JTextField();
        txtptests = new javax.swing.JTextField();
        txtpdetailsofprescribedtreatments = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnshowdetails = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtpfirstname = new javax.swing.JTextField();
        btnlogoff = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Patient Information");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 20, 390, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Patient's Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 290, 320, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Patient's Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 330, 320, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Patient's Telephone");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 370, 320, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Recommended person's ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 410, 320, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Recommended person's Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 450, 320, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Patient's Ward");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(180, 490, 320, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Registration Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(180, 530, 320, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Patient's Tests");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(180, 570, 320, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Details of Prescribed Treatments");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(180, 600, 320, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Enter the Patient's Registration Id");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(180, 110, 320, 40);

        txtplastname.setBackground(new java.awt.Color(153, 255, 153));
        txtplastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtplastname);
        txtplastname.setBounds(530, 290, 710, 30);

        txtpaddress.setBackground(new java.awt.Color(153, 255, 153));
        txtpaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpaddress);
        txtpaddress.setBounds(530, 330, 710, 30);

        txtptelephone.setBackground(new java.awt.Color(153, 255, 153));
        txtptelephone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtptelephone);
        txtptelephone.setBounds(530, 370, 710, 30);

        txtrecommendedpersonid.setBackground(new java.awt.Color(153, 255, 153));
        txtrecommendedpersonid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtrecommendedpersonid);
        txtrecommendedpersonid.setBounds(530, 410, 710, 30);

        txtrecommendedpersonname.setBackground(new java.awt.Color(153, 255, 153));
        txtrecommendedpersonname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtrecommendedpersonname);
        txtrecommendedpersonname.setBounds(530, 450, 710, 30);

        txtpward.setBackground(new java.awt.Color(153, 255, 153));
        txtpward.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpward);
        txtpward.setBounds(530, 490, 710, 30);

        txtpregistrationdate.setEditable(false);
        txtpregistrationdate.setBackground(new java.awt.Color(153, 255, 153));
        txtpregistrationdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpregistrationdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpregistrationdateActionPerformed(evt);
            }
        });
        jPanel1.add(txtpregistrationdate);
        txtpregistrationdate.setBounds(530, 530, 710, 30);

        txtptests.setBackground(new java.awt.Color(153, 255, 153));
        txtptests.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtptests);
        txtptests.setBounds(530, 570, 710, 30);

        txtpdetailsofprescribedtreatments.setBackground(new java.awt.Color(153, 255, 153));
        txtpdetailsofprescribedtreatments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpdetailsofprescribedtreatments);
        txtpdetailsofprescribedtreatments.setBounds(530, 610, 710, 30);

        txtpid.setBackground(new java.awt.Color(153, 255, 153));
        txtpid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpid);
        txtpid.setBounds(530, 120, 710, 30);

        btnclear.setBackground(new java.awt.Color(51, 255, 102));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(980, 210, 260, 30);

        btnshowdetails.setBackground(new java.awt.Color(51, 255, 102));
        btnshowdetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnshowdetails.setText("Search");
        btnshowdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnshowdetails);
        btnshowdetails.setBounds(670, 210, 260, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("OR");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1320, 110, 90, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Patient's First Name");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(180, 150, 320, 40);

        txtpfirstname.setBackground(new java.awt.Color(153, 255, 153));
        txtpfirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpfirstname);
        txtpfirstname.setBounds(530, 160, 710, 30);

        btnlogoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogoff.setForeground(new java.awt.Color(255, 0, 0));
        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/13165939071654987882logout-md.png"))); // NOI18N
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogoff);
        btnlogoff.setBounds(1270, 10, 70, 70);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 0, 0));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/home.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(1190, 10, 70, 70);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/green_background_2-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowdetailsActionPerformed
        // show detais of the employee:
        String id=txtpid.getText();
        String fname=txtpfirstname.getText();
        
        try{
            //creaate a database connection
            Class.forName("java.sql.Driver");
            String path="jdbc:mysql://localhost/hospital_database";
            String user="root";
            String pass="root";
            Connection con = DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement();
            
            //select data
            String query ="select * from patient where Reg_id='"+id+"' or First_name='"+fname+"'";
            ResultSet rs=stmt.executeQuery(query);
            
            //set text box using fetched data
            while(rs.next()){
                txtpid.setText(rs.getString("Reg_id"));
                txtpfirstname.setText(rs.getString("First_name"));
                txtplastname.setText(rs.getString("Last_name"));
                txtpaddress.setText(rs.getString("Address"));
                txtptelephone.setText(rs.getString("Telephone_no"));
                txtrecommendedpersonid.setText(rs.getString("Recommendation_id"));
                txtrecommendedpersonname.setText(rs.getString("Recommendatation_name"));
                txtpward.setText(rs.getString("Ward"));
                txtpregistrationdate.setText(rs.getString("Registration_date"));
                txtptests.setText(rs.getString("Tests"));
                txtpdetailsofprescribedtreatments.setText(rs.getString("Prescribed_treatments"));
                
                
            }
        }catch(ClassNotFoundException | SQLException ex){
            //error messgae
            JOptionPane.showMessageDialog(null,"Error Found"+ex);
        }
        
        
        
    }//GEN-LAST:event_btnshowdetailsActionPerformed

    private void txtpregistrationdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpregistrationdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpregistrationdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // clear data:
        txtpid.setText("");
        txtplastname.setText("");
        txtpfirstname.setText("");
        txtpaddress.setText("");
        txtptelephone.setText("");
        txtrecommendedpersonid.setText("");
        txtrecommendedpersonname.setText("");
        txtpward.setText("");
        txtpregistrationdate.setText("");
        txtptests.setText("");
        txtpdetailsofprescribedtreatments.setText("");
                
        
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // hide this and go to home frame:
        this.hide();
        admin_page admin=new admin_page();
        admin.setVisible(true);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        //hide this and go to login frame:
        this.hide();
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnlogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show_patient_information_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show_patient_information_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show_patient_information_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show_patient_information_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show_patient_information_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogoff;
    private javax.swing.JButton btnshowdetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtpaddress;
    private javax.swing.JTextField txtpdetailsofprescribedtreatments;
    private javax.swing.JTextField txtpfirstname;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtplastname;
    private javax.swing.JTextField txtpregistrationdate;
    private javax.swing.JTextField txtptelephone;
    private javax.swing.JTextField txtptests;
    private javax.swing.JTextField txtpward;
    private javax.swing.JTextField txtrecommendedpersonid;
    private javax.swing.JTextField txtrecommendedpersonname;
    // End of variables declaration//GEN-END:variables
}
