/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.reception;

import hospital.admin.*;
import hospital.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pramodaya jayalath
 */
public class patient_registration_frame extends javax.swing.JFrame {

    /**
     * Creates new form patient_registration_frame
     */
    public patient_registration_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttelephoneno = new javax.swing.JTextField();
        txtrecommendationid = new javax.swing.JTextField();
        txtrecommendationname = new javax.swing.JTextField();
        txtregistrationdate = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        btnlogoff = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        comboboxpatientward = new javax.swing.JComboBox<>();
        txtaddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Registration date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 490, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Patient's  Details");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 40, 330, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("First Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 210, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Recommendation Id");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 370, 210, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Recommendation Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 410, 230, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Ward");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(300, 450, 210, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Address");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(300, 290, 210, 30);

        txttelephoneno.setBackground(new java.awt.Color(153, 255, 153));
        txttelephoneno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txttelephoneno);
        txttelephoneno.setBounds(610, 330, 640, 30);

        txtrecommendationid.setBackground(new java.awt.Color(153, 255, 153));
        txtrecommendationid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtrecommendationid);
        txtrecommendationid.setBounds(610, 370, 640, 30);

        txtrecommendationname.setBackground(new java.awt.Color(153, 255, 153));
        txtrecommendationname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtrecommendationname);
        txtrecommendationname.setBounds(610, 410, 640, 30);

        txtregistrationdate.setBackground(new java.awt.Color(153, 255, 153));
        txtregistrationdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtregistrationdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrationdateActionPerformed(evt);
            }
        });
        jPanel1.add(txtregistrationdate);
        txtregistrationdate.setBounds(610, 490, 640, 30);

        txtfirstname.setBackground(new java.awt.Color(153, 255, 153));
        txtfirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtfirstname);
        txtfirstname.setBounds(610, 210, 640, 30);

        btnclear.setBackground(new java.awt.Color(51, 255, 102));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(1070, 550, 180, 50);

        btnsave.setBackground(new java.awt.Color(51, 255, 102));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(840, 550, 180, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Telephone No");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 330, 210, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Last Name");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(300, 250, 210, 30);

        txtlastname.setBackground(new java.awt.Color(153, 255, 153));
        txtlastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtlastname);
        txtlastname.setBounds(610, 250, 640, 30);

        btnlogoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogoff.setForeground(new java.awt.Color(255, 0, 0));
        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/13165939071654987882logout-md.png"))); // NOI18N
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogoff);
        btnlogoff.setBounds(1250, 20, 70, 70);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 0, 0));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/home.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(1170, 20, 70, 70);

        comboboxpatientward.setBackground(new java.awt.Color(0, 255, 0));
        comboboxpatientward.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxpatientward.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Maternity", "Pediatrics", "Oncology", "Gynecologyst" }));
        comboboxpatientward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxpatientwardActionPerformed(evt);
            }
        });
        jPanel1.add(comboboxpatientward);
        comboboxpatientward.setBounds(610, 450, 640, 30);

        txtaddress.setBackground(new java.awt.Color(153, 255, 153));
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtaddress);
        txtaddress.setBounds(610, 290, 640, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/green_background_2-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // save patients data:
        
        String fname =txtfirstname.getText();
        String lname =txtlastname.getText();
        String address =txtaddress.getText();
        String phone =txttelephoneno.getText();
        String recommendtaionid =txtrecommendationid.getText();
        String recommendtaionname =txtrecommendationname.getText();
        String ward =comboboxpatientward.getSelectedItem().toString();
        String registrationdate=txtregistrationdate.getText();
        
        try{
            //create a database connetion
            Class.forName("java.sql.Driver");
            String path="jdbc:mysql://localhost/hospital_database";
            String user="root";
            String pass="root";
            Connection con = DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement();
            
            //insert data in to the patient table
            String query ="insert into patient(First_name,Last_name,Address,Telephone_no,Recommendation_id,Recommendatation_name,Ward,Registration_date) values('"+fname+"','"+lname+"','"+address+"','"+phone+"','"+recommendtaionid+"','"+recommendtaionname+"','"+ward+"','"+registrationdate+"')";
            stmt.executeUpdate(query);
            
            //confirmatin message
            JOptionPane.showMessageDialog(null,"Succesfully inserted");
            
            //clear text box
            txtfirstname.setText("");
            txtlastname.setText("");
            txtaddress.setText("");
            txttelephoneno.setText("");
            txtrecommendationid.setText("");
            txtrecommendationname.setText("");
            txtregistrationdate.setText("");
        
        
        }catch(Exception ex){
            //error message
            JOptionPane.showMessageDialog(null,"Error Found"+ex);
        }
                
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // clear text box:
        txtfirstname.setText("");
        txtlastname.setText("");
        txtaddress.setText("");
        txttelephoneno.setText("");
        txtrecommendationid.setText("");
        txtrecommendationname.setText("");
        txtregistrationdate.setText("");
        
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtregistrationdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrationdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrationdateActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // go to recrpton home frame:
        this.hide();
        reception_page reception=new reception_page();
        reception.setVisible(true);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        // hide this and go to login frame:
         this.hide();
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnlogoffActionPerformed

    private void comboboxpatientwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxpatientwardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxpatientwardActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient_registration_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient_registration_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient_registration_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient_registration_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient_registration_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogoff;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> comboboxpatientward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtrecommendationid;
    private javax.swing.JTextField txtrecommendationname;
    private javax.swing.JTextField txtregistrationdate;
    private javax.swing.JTextField txttelephoneno;
    // End of variables declaration//GEN-END:variables
}
