/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;
import hospital.reception.reception_page;
import hospital.register_page;
import hospital.admin.admin_page;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author pramodaya jayalath
 */
public class Login extends javax.swing.JFrame {


    
    /**
     * Creates new form Login
     */
    public Login() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        btnexit = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(522, 311));

        jPanel1.setMinimumSize(new java.awt.Dimension(522, 311));
        jPanel1.setPreferredSize(new java.awt.Dimension(522, 311));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        jLabel2.setPreferredSize(new java.awt.Dimension(522, 311));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 140, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("User Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(522, 311));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 90, 100, 30);

        txtusername.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtusername);
        txtusername.setBounds(350, 90, 160, 30);

        btnexit.setBackground(new java.awt.Color(51, 255, 0));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit);
        btnexit.setBounds(370, 220, 100, 30);

        btnlogin.setBackground(new java.awt.Color(51, 255, 0));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(250, 220, 100, 30);

        txtpassword.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(txtpassword);
        txtpassword.setBounds(350, 140, 160, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/login-icon-png-27.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 40, 260, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/img/fresh_green_grass_11-wallpaper-1366x768.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 2));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 75));
        jLabel1.setPreferredSize(new java.awt.Dimension(522, 311));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        //get username and password:
        String username=txtusername.getText();
        String password=txtpassword.getText();
        
        //if admin 
        if(username.contains("admin")&&password.contains("admin")){
            
            //clear 
            txtusername.setText("");
            txtpassword.setText("");
            
            //dispose this and show admin home frame
            this.dispose();
            admin_page adminpage=new admin_page();
            adminpage.setVisible(true);
            
         //if reception  
        }else if(username.contains("reception")&& password.contains("reception")){
            
            //clear text box
            txtusername.setText("");
            txtpassword.setText("");
            
            //dispose this and show reception frame
            this.dispose();
            reception_page receptionpage=new reception_page();
            receptionpage.setVisible(true);
            
         //if register   
        }else if(username.contains("register")&& password.contains("register")){
            
            //clear text box
            txtusername.setText("");
            txtpassword.setText("");
            
            //dispose this and show registe frame
            this.dispose();
            register_page registerpage=new register_page();
            registerpage.setVisible(true);
            
        }else{
            //error message
            JOptionPane.showMessageDialog(null,"Invalid UseName or Password");
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
